atlantis:
  githubApp:
    id: "2654766"
    slug: bymv-atlantis
  orgAllowlist: "github.com/MoralesV93/bymv-frontend-pbrand"
  vcsSecretName: atlantis-vcs
  extraPath: "/atlantis-data/bin"
  extraVolumeMounts:
    - name: tf-vars-volume
      mountPath: /atlantis-data/tfvars
      readOnly: true
  extraVolumes:
    - name: tf-vars-volume
      secret:
        secretName: atlantis-tf-vars
  awsSecretName: atlantis-aws-cred
  environment:
    ATLANTIS_DEFAULT_TF_VERSION:  1.3.0
    TF_VAR_FILE: /atlantis-data/tfvars/terraform.tfvars
  repoConfig: |
    ---
    repos:
    - id: github.com/MoralesV93/bymv-frontend-pbrand
      apply_requirements: [approved, mergeable, undiverged]
      allowed_overrides: [apply_requirements,workflow]
      allow_custom_workflows: true